sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t smktech/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true smktech/docker-react npm run test